# Generated by Django 3.2.4 on 2021-07-09 02:16
#이 파일은 변화를 반영하는 파일임. 이 파일 삭제하면 안됨. db를 밀고 싶은 게 아니면 놉놉
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
    ]
